### ISSUE TITLE
node-exporter-ds.yaml uses hostPath which DO does not recommend/work

### ISSUE THREAD

**Issue by JamesReate** [do-community/doks-monitoring#7]
node-exporter-ds.yaml lines 57+ need to be updated to use cephs.
Per:
https://www.digitalocean.com/docs/kubernetes/resources/clusterlint-errors/#hostpath-volume
hostpath is not recommended by DO. 
This might be related to error being reported by customers on December 23rd 2019 (comments section):
https://www.digitalocean.com/community/tutorials/how-to-set-up-a-kubernetes-monitoring-stack-with-prometheus-grafana-and-alertmanager-on-digitalocean

**Comment by JamesReate** [comment]
After investigating more, error reported when installing prometheus is due to there not being a `storageClassName` called `default`. This is different than there being a default storage class. For compatibility in kubernetes the default storage class should also be called default, you can do this:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: default
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
